language: perl
perl:
  - "5.24-shrplib"
dist: xenial
sudo: false # faster builds as long as you don't need sudo access
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - build-essential
    - sqlite3
    - libdbi-perl
    - libdbd-sqlite3-perl

